language: ruby
env:
  - USE_OFFICIAL_GEM_SOURCE=1

services:
  - mysql

rvm:
  - 2.6.3

gemfile:
  - gemfiles/Gemfile-5-2
  - gemfiles/Gemfile-6-0

before_script:
  - bundle install
  - RAILS_ENV=test bundle exec rake db:create
  - RAILS_ENV=test bundle exec rake db:migrate

script: RAILS_ENV=test bundle exec rails test
